### ISSUE TITLE
By May of 2024, does this project support iPhone browser?

### ISSUE THREAD

**Issue by WENPIN1** [peaBerberian/wasp-hls#9]
By May of 2024, does this project support iPhone browser?

I checked the demo on iphone, but it has a MediaSourceAttachmentError.

![photo_2024-05-16_15-19-24](https://github.com/peaBerberian/wasp-hls/assets/13994729/d0ddeb1c-2061-4c9c-b3cb-5b24e67f5ea3)

Thanks for your help!

**Comment by peaBerberian** [comment]
Hi (sorry for the very late response! This POC fulfilled its role and I'm since into low-maintenance mode on it),

I think that the `MediaSource` API on which we rely here to feed media data to the browser is not available on iPhones. Apple chose to implement an alternative, `ManagedMediaSource` (https://webkit.org/blog/14735/webkit-features-in-safari-17-1/).

Quickly, I don't see why we couldn't alternatively rely on `ManagedMediaSource` (which has some other requirements), but I don't have any iOS device to properly test it :/

Though if you (or anyone) want to implement this in this project, you can provide a pull request to it or fork that project to adapt it to your need, I have 0 issue with that (on the contrary).

**Comment by WENPIN1** [comment]
Thank you for your handsome efforts very much!
